// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DTS_Project.Domain.Models
{
    public partial class Ville
    {
        [Key]
        public long Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Nom { get; set; }

        [Column("Created_at")]
        public DateTime? CreatedAt { get; set; }

        [Column("Updated_at")]
        public DateTime? UpdatedAt { get; set; }
    }
}