version: '3.4'

services:
  dts-project_web:
    image: ${DOCKER_REGISTRY-}dts-project
    container_name: dts-project_web
    build:
      context: .
      dockerfile: DTS-Project.WebApi/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    depends_on:
      - dts_database

  dts_database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    #volumes:
    #  - .\dts_database:C:\docker
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "2Secure*Password2"
      ACCEPT_EULA: "Y"
